# apps/my-kubernetes-app/kubernetes/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: placeholder-namespace # Will be overridden by instance
resources:
  - deployment.yaml
  - service.yaml
# commonLabels:
#   app.kubernetes.io/name: my-kubernetes-app
