apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  central_config.json: |
    {
        "service_name": "crypto_trader_main",
        "database": {
            "type": "postgresql",
            "host": "YOUR_POSTGRESQL_HOST",
            "port": 5432,
            "name": "YOUR_POSTGRESQL_DBNAME"
        },
        "exchanges": [
            {
                "name": "binance",
                "extra_settings": {
                    "simulation": true
                }
            }
        ],
        "slack": {
            "default_channel_id": "YOUR_SLACK_CHANNEL_ID_PLACEHOLDER"
        },
        "algorithms": [
            {
                "name": "default_algo",
                "parameters": {
                    "maxLost": {
                        "percentage": 3,
                        "percentage_update": 0.25,
                        "mean": 720
                    },
                    "takeProfit": {
                        "percentage": 5.0
                    },
                    "AIAlgo": {
                        "enabled": true,
                        "model_path": "./models/ai_algo_model.pth"
                    }
                }
            }
        ],
        "other_settings": {
            "currency": "BTCUSDT",
            "transaction_amount": 100,
            "delay_seconds": 60,
            "initial_capital": 0.0
        },
        "notification_service_url": "http://notification-service-svc:8001"
    }
