apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service-container
        image: your-docker-registry/notification-service:latest # Placeholder - update with actual image
        ports:
        - containerPort: 8001
        env:
        - name: APP_CONFIG_FILE_PATH
          value: "/etc/config/central_config.json"
        # Inject all keys from postgres-secret as environment variables
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        # Inject SLACK_BOT_TOKEN from slack-secret
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: BOT_TOKEN
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
  labels:
    app: notification-service
spec:
  type: ClusterIP # Exposes the service on an internal IP in the cluster
  selector:
    app: notification-service # Matches the labels of the pods
  ports:
  - protocol: TCP
    port: 8001 # Port on which the service is available internally
    targetPort: 8001 # Port on the pod/container that the service forwards traffic to
