apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password123" # Replace with a strong password, ideally from a secure generation process
  POSTGRES_DB: "trading_db" # Optional: define a default database
