apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
  labels:
    app: trading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-service
  template:
    metadata:
      labels:
        app: trading-service
    spec:
      containers:
      - name: trading-service-container
        image: your-docker-registry/trading-service:latest # Placeholder - update with actual image
        ports:
        - containerPort: 8000
        env:
        # Config file path - Central config will be read from here
        - name: APP_CONFIG_FILE_PATH
          value: "/etc/config/central_config.json"
        # Database credentials from postgres-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        # Binance API credentials from binance-secret
        - name: BINANCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: binance-secret
              key: API_KEY
        - name: BINANCE_API_SECRET
          valueFrom:
            secretKeyRef:
              name: binance-secret
              key: API_SECRET
        # Slack Bot Token from slack-secret
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secret
              key: BOT_TOKEN
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        # - name: trading-db-storage # This might not be needed if DB is external
        #   mountPath: /app/data
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      # - name: trading-db-storage # This might not be needed if DB is external
      #   persistentVolumeClaim:
      #     claimName: trading-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: trading-service-svc
  labels:
    app: trading-service
spec:
  type: ClusterIP # Exposes the service on an internal IP in the cluster
  selector:
    app: trading-service # Matches the labels of the pods
  ports:
  - protocol: TCP
    port: 8000 # Port on which the service is available internally
    targetPort: 8000 # Port on the pod/container that the service forwards traffic to
