"""create_initial_tables_autogen

Revision ID: 78900d50a4a8
Revises:
Create Date: 2025-06-05 16:08:00.225519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78900d50a4a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_ticks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_ticks_currency_pair'), 'price_ticks', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_price_ticks_timestamp'), 'price_ticks', ['timestamp'], unique=False)
    op.create_table('rolling_mean_pricings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True, comment='Period of the rolling mean, e.g., 20 for a 20-period SMA'),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=True, comment='The calculated mean value'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolling_mean_pricings_currency_pair'), 'rolling_mean_pricings', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_rolling_mean_pricings_timestamp'), 'rolling_mean_pricings', ['timestamp'], unique=False)
    op.create_table('trading_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('buy_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_value_eur', sa.Numeric(precision=18, scale=8), nullable=True, comment='Total value of the buy in quote currency, e.g., EUR or USD'),
    sa.Column('buy_fee_eur', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency_pair', sa.String(length=20), nullable=True),
    sa.Column('base_currency_bought_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('base_currency_buy_price', sa.Numeric(precision=18, scale=8), nullable=True, comment='Price per unit of base currency at time of buy'),
    sa.Column('sell_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_currency_sell_price', sa.Numeric(precision=18, scale=8), nullable=True, comment='Price per unit of base currency at time of sell'),
    sa.Column('sell_fee_eur', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('profit_eur', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_transactions_currency_pair'), 'trading_transactions', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_trading_transactions_task_id'), 'trading_transactions', ['task_id'], unique=False)
    op.create_table('max_lost_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('initial_base_currency_buy_price', sa.Numeric(precision=18, scale=8), nullable=True, comment='Buy price of the base currency for this transaction'),
    sa.Column('current_min_gain_percentage', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('current_min_value_threshold', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['trading_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_max_lost_settings_transaction_id'), 'max_lost_settings', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_max_lost_settings_transaction_id'), table_name='max_lost_settings')
    op.drop_table('max_lost_settings')
    op.drop_index(op.f('ix_trading_transactions_task_id'), table_name='trading_transactions')
    op.drop_index(op.f('ix_trading_transactions_currency_pair'), table_name='trading_transactions')
    op.drop_table('trading_transactions')
    op.drop_index(op.f('ix_rolling_mean_pricings_timestamp'), table_name='rolling_mean_pricings')
    op.drop_index(op.f('ix_rolling_mean_pricings_currency_pair'), table_name='rolling_mean_pricings')
    op.drop_table('rolling_mean_pricings')
    op.drop_index(op.f('ix_price_ticks_timestamp'), table_name='price_ticks')
    op.drop_index(op.f('ix_price_ticks_currency_pair'), table_name='price_ticks')
    op.drop_table('price_ticks')
    # ### end Alembic commands ###
